<a href="https://colab.research.google.com/github/ddekun/Linear_algebra/blob/lesson3/lesson3/hw3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Линейные преобразования

In [ ]:
import numpy as np

### __1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [ ]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}\cdot \begin{pmatrix}x\\ y\end{pmatrix}=\lambda\cdot \begin{pmatrix}x\\ y\end{pmatrix}
\begin{pmatrix}
-x\\ 
-y
\end{pmatrix}=\begin{pmatrix}\lambda x\\ \lambda y\end{pmatrix}
\begin{cases}-x=\lambda x\\-y=\lambda y\end{cases}
\lambda=-1$$

Решение не зависит от значений $x$ и $y$, следовательно для оператора поворота любой вектор является собственным.

In [ ]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


### __3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}\cdot\begin{pmatrix}1\\1\end{pmatrix}=\lambda\cdot\begin{pmatrix}1\\1\end{pmatrix} \Rightarrow\begin{cases}1+1=\lambda \\
-1+3=\lambda \end{cases}\Rightarrow \lambda=2$$

Вектор $x=(1,1)$ является собственным вектором оператора $A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}$
 , с собственным значением $\lambda=2$.

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}\cdot \begin{pmatrix}3\\-3\\-4\end{pmatrix}=\lambda \cdot\begin{pmatrix}3\\-3\\-4\end{pmatrix}\Rightarrow
\begin{cases}-9=3\lambda\\9=-3\lambda\\-12=-4\lambda\end{cases}\Rightarrow
\begin{cases}\lambda=-3\\\lambda=-3\\\lambda=3\end{cases}$

Такая система не имеет смысла, следовательно, вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.