<a href="https://colab.research.google.com/github/ddekun/Linear_algebra/blob/lesson2/lesson2/hw2_1_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Матрицы и матричные операции. Часть 1

In [19]:
import numpy as np

### __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__Решение__<br>
a) Произведения матриц $AB$  и  $BA$ не определены, так как столбцы матрицы A не соответствуют строкам матрицы B и наоборот.<br>
б) Произведения матриц $AB$ - определены и имеют размер 2x3. Произведения матриц $BA$ не определены, так как столбцы матрицы B не соответствуют строкам матрицы A.<br>
в) Произведения матриц $AB$ - определены и имеют размер 8x8. Произведения матриц $BA$ - определены и имеют размер 3x3.<br>
г) Произведения матриц $AB$  и  $BA$ определены и имеют размер 4x4.

### __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Решение__<br>
$$A + B =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.$$
$$A \cdot B =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1\cdot 4 + (-2)\cdot 0 & 1\cdot(-1) + (-2)\cdot 5\\ 
3\cdot 4 + 0\cdot 0 & 3\cdot(-1) + 0\cdot 5
\end{pmatrix} = 
\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$$
$$B \cdot A =\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \cdot
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = 
\begin{pmatrix}
4\cdot 1 + (-1)\cdot 3 & 4\cdot(-2) + (-1)\cdot 0\\ 
0\cdot 1 + 5\cdot 3 & 0\cdot(-2) + 5\cdot 0
\end{pmatrix} = 
\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}.$$

__Решение c numpy__

In [20]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Сумма матриц:\n{A+B}')
print(f'Произведение матриц A*B:\n{A@B}')
print(f'Произведение матриц B*A:\n{B@A}')

Сумма матриц:
[[ 5 -3]
 [ 3  5]]
Произведение матриц A*B:
[[  4 -11]
 [ 12  -3]]
Произведение матриц B*A:
[[ 1 -8]
 [15  0]]


### __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__Решение__<br>
$$3A-2B+4C=3\cdot
\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}-2\cdot\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+4\cdot\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
1\cdot3 & 7\cdot3\\ 
3\cdot3 & -6\cdot3
\end{pmatrix}-\begin{pmatrix}
0\cdot2 & 5\cdot2\\ 
2\cdot2 & -1\cdot2
\end{pmatrix}+\begin{pmatrix}
2\cdot4 & -4\cdot4\\ 
1\cdot4 & 1\cdot4
\end{pmatrix}=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}-\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}+\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}=\begin{pmatrix}
3-0+8 & 21-10-16\\ 
9-4+4 & -18+2+4
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$$

__Решение c numpy__

In [21]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Линейная комбинация 3A-2B+4C будет равна\n{3*A-2*B+4*C}')

Линейная комбинация 3A-2B+4C будет равна
[[ 11  -5]
 [  9 -12]]


### __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$. Вычислить $AA^{T}$ и $A^{T}A$.

__Решение__<br>
$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}.$

$AA^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}\cdot
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}=
\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\ 
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}.$

$A^{T}A=
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}\cdot
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}=
\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}.$

__Решение c numpy__

In [22]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [23]:
trans_A = A.T
trans_A

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [24]:
A@trans_A

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [25]:
trans_A@A

array([[45,  0],
       [ 0, 14]])

### __5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [26]:
def multiplicate_matrix(left,right):
    try: 
        left.shape[1]==right.shape[0]
        result=[]
        temp=[]
        s=0
        for i in range(left.shape[0]):
            for j in range(right.shape[1]):
                for k in range(right.shape[0]):
                    s+=left[i][k]*right[k][j]
                temp.append(s)
                s=0
            result.append(temp)
            temp=[]
        return np.array(result)
    except Exception:
        print('Произведение матриц таких размеров не определено!')

In [27]:
A=np.array([[1, 3], [3, 4], [2, 5], [1, 7]])
B=np.array([[3, -2, 1, 4], [0 , 6, 1, -1]])

In [28]:
A@B

array([[ 3, 16,  4,  1],
       [ 9, 18,  7,  8],
       [ 6, 26,  7,  3],
       [ 3, 40,  8, -3]])

In [29]:

multiplicate_matrix(A,B)

array([[ 3, 16,  4,  1],
       [ 9, 18,  7,  8],
       [ 6, 26,  7,  3],
       [ 3, 40,  8, -3]])

In [30]:
B@A

array([[ 3, 34],
       [19, 22]])

In [31]:

multiplicate_matrix(B,A)

array([[ 3, 34],
       [19, 22]])

# Матрицы и матричные операции. Часть 2

### __1.__ Вычислить определитель:

   a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$

   б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$
    
   в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$

a) __Решение__<br>
Если порядок матрицы равен $2$, то есть матрица имеет вид

$$A=\begin{pmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{pmatrix}.$$
Определитель матрицы $A$ обозначается как $detA$, или $|A|$, то есть определитель второго порядка можно записать как

$$detA=|A|=\begin{vmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{vmatrix}=a_{11}a_{22} - a_{12}a_{21}.$$
Тогда:<br>
$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$<br>
$sinx\cdot sinx -(-cosx)cosx=sin^2x+cos^2x=1;$

__Решение c numpy__

In [32]:
A=np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
np.linalg.det(A)

0.9999999999999999

б) __Решение__<br>

Определитель матрицы треугольного вида равен произведению элементов, стоящих на ее главной диагонали.<br>
$detB=4\cdot5\cdot9=180$

__Решение c numpy__

In [33]:
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])  
np.linalg.det(B)

180.0

в) __Решение__<br>
Разложим по элементам первой строки:<br>
$detC=1⋅\begin{pmatrix}
5 & 6\\
8 & 9
\end{pmatrix}-2⋅\begin{pmatrix}
4 & 6\\
7 & 9
\end{pmatrix}+3\cdot\begin{pmatrix}
4 & 5\\
7 & 8
\end{pmatrix}=1⋅(5⋅9-6\cdot8)-2⋅(4⋅9-6\cdot7+3⋅(4⋅8-5\cdot7)=0$

__Решение c numpy__

In [34]:
C=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  
np.linalg.det(C)

0.0

### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

 __Решение__<br>
a) Для двух квадратных матриц одинакового размера

$det(AB)=detA\cdot detB.$

$det(A^2)=det(A\cdot A)=det(A)\cdot det(A)=4\cdot4=16$

б) Определитель транспонированной матрицы равен определителю исходной:

$detA^{T}=detA$

$detA^{T}=4$

в)Умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число.

$det(2A)=2\cdot4=8$

### __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__Решение__<br>
Поскольку мы можем представить вторую строку данной матрицы $(4,-14,6)$через первую строку $(-2,7,-3)$ как $(4,-14,6)=-2⋅(-2,7,-3)$, т.е. две строки (столбца) матрицы линейно зависимы, а значит её определитель равен 0, т.е.
такая матрица, согласно определению, является вырожденной.

__Решение c numpy__

In [35]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3 , 7, 13]])
np.linalg.det(A)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Решение__<br>
а)Третья строка является суммой первой и второй строк, а значит, ее можно отбросить:

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$

Из первой строки вычтем вторуюб и поменяем строки местами:

$\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix}$

Ранг матрицы равен $2$

__Решение c numpy__

In [36]:
A = np.array([[1,2,3],[1,1,1],[2,3,4]])
np.linalg.matrix_rank(A)

2

б) __Решение__<br>
Третья строка является суммой первой и второй строки, отбрасываем:

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Вычтем вторую строку из первой:

$\begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Удалим второй столбец, который можно выразить через первый:

$\begin{pmatrix}
0 & 0 & -1\\ 
0 & 2 & 2\\ 
2 & 5 & 6
\end{pmatrix}$

Поменяем местами первую и третью строки:

$\begin{pmatrix}
2 & 5 & 6\\ 
0 & 2 & 2\\ 
0 & 0 & -1
\end{pmatrix}$

Ранг матрицы равен $3$

__Решение c numpy__

In [37]:
B = np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
np.linalg.matrix_rank(B)

3