<a href="https://colab.research.google.com/github/ddekun/Linear_algebra/blob/lesson5/lesson5/hw5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Сингулярное разложение матриц

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])

In [3]:
U, s, W = np.linalg.svd(A)

In [4]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [5]:
print(f'Матрица A:\n{A}')
print(f'Матрица U:\n{U}')
print(f'Матрица D:\n{D}')
print(f'Матрица V:\n{W.T}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [9]:
# Проведем проверку
U@D@W

array([[ 1.,  2.,  0.],
       [ 0., -0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [-0.,  1., -0.]])

### 2. Для матрицы из предыдущего задания найти:
а) евклидову норму;

In [10]:
np.linalg.norm(A, ord=2)

8.824868854820444

б) норму Фробениуса.

В случае, когда известно сингулярное разложение матрицы, ее норма Фробениуса вычисляется как

$$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}.$$

In [12]:
U,s,W = np.linalg.svd(A)

In [13]:
frob_norm = np.sqrt(np.sum(s**2))
print(f'Норма фробениуса для матрицы A:\n{frob_norm}')

Норма фробениуса для матрицы A:
11.045361017187263


Найдем стандартным методом модуля linalg:

In [15]:
print(f"Норма фробениуса для матрицы A:\n{np.linalg.norm(A, ord='fro')}")

Норма фробениуса для матрицы A:
11.045361017187261
